trigger:
- main

pool:
  name: Default
  vmImage: azdo-agent

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: pip install requests

    - task: AzureCLI@2
      inputs:
        azureSubscription: codeowner-admin
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: ./codeowners.py -r $(Build.Repository.ID)

