trigger:
- main

pool:
  ubuntu-22.04

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: codeowner-admin
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: ./codeowners.py -r pipeline-commons

