trigger:
- main

pool:
  name: Default
  vmImage: azdo-agent

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: pip3 install -g pipenv

    - script: pipenv lock -r > requirements.txt
      displayName: 'Create requirements.txt from Pipfile'

    - script: pip install -r requirements.txt
      displayName: 'Install requirements.txt'

    - task: AzureCLI@2
      inputs:
        azureSubscription: codeowner-admin
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: ./codeowners.py -r $(Build.Repository.ID)

