trigger:
  branches:
    include:
    - main
  paths:
    include:
    - CODEOWNERS.json

resources:
  repositories:
    - repository: test-app
      type: git
      name: SHB-test/test-app
      ref: main
      trigger:
        paths:
          include:
            - CODEOWNERS.json

pool:
  vmImage: ubuntu-22.04

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - checkout: self
      persistCredentials: true

    - checkout: test-app

    - script: az config set extension.use_dynamic_install=yes_without_prompt
      displayName: 'configure azure cli'

    - script: env

    - task: AzureCLI@2
      enabled: false
      inputs:
        azureSubscription: codeowner-admin
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: ./codeowners.py -r $(Build.Repository.ID)

