trigger:
  branches:
    include:
    - main
  paths:
    include:
    - CODEOWNERS.json

pool:
  name: Default
  vmImage: azdo-agent

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - checkout: self
      clean: true
      persistCredentials: true

    - script: az config set extension.use_dynamic_install=yes_without_prompt
      displayName: 'configure azure cli'

    - task: AzureCLI@2
      inputs:
        azureSubscription: codeowner-admin
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: ./codeowners.py -r $(Build.Repository.ID)

