parameters:
- name: repos
  type: object

stages:
- stage: Build
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')  # TODO: change to master after move
  jobs:
  - job: Build
    steps:
    - checkout: self
      persistCredentials: true

    - ${{ each repo in parameters.repos }}:
      - checkout: ${{ repo }}
        condition: eq(variables['Build.Repository.Name'], '${{ repo }}')

    - script: az config set extension.use_dynamic_install=yes_without_prompt
      displayName: 'configure azure cli'

    - task: AzureCLI@2
      inputs:
        azureSubscription: codeowner-admin
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: ./pipeline-commons/codeowners.js
      env:
        ORG: jagekransdev
        PROJECT: SHB-test
        REPO_ID: $(Build.Repository.ID)
        CODEOWNERS_FILE: ./$(Build.Repository.Name)/CODEOWNERS.json
        ACCESS_TOKEN: $(System.AccessToken)
